/**
 * Parse the bundled pick_profiles.scad into polygon points and SVG paths
 * for UI thumbnails. The file is generated by tools/svg_to_profile.py and
 * has a very regular shape — we do not need a full OpenSCAD parser.
 */
import profilesSource from './pick_profiles.scad?raw'
import type { PickTypeName } from './pick-types'
import { PICK_TYPE_NAMES } from './pick-types'

export type Point2 = [number, number]

function parseProfiles(source: string): Record<string, Point2[]> {
  const result: Record<string, Point2[]> = {}
  const entryRe =
    /\["([A-Za-z_][A-Za-z0-9_]*)",\s*\[([\s\S]*?)\]\s*\]/g
  let match: RegExpExecArray | null
  while ((match = entryRe.exec(source)) !== null) {
    const name = match[1]
    const body = match[2]
    const points: Point2[] = []
    const pointRe = /\[\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\]/g
    let pm: RegExpExecArray | null
    while ((pm = pointRe.exec(body)) !== null) {
      points.push([Number(pm[1]), Number(pm[2])])
    }
    if (points.length > 0) result[name] = points
  }
  return result
}

const PROFILE_POINTS = parseProfiles(profilesSource)

export function profilePoints(name: PickTypeName): Point2[] {
  const pts = PROFILE_POINTS[name]
  if (!pts) {
    throw new Error(`no outline for pick type: ${name}`)
  }
  return pts
}

/** Build an SVG path string in the unit box centred on the origin. */
export function svgPathFor(name: PickTypeName): string {
  const pts = profilePoints(name)
  if (pts.length === 0) return ''
  const [x0, y0] = pts[0]
  // SVG Y grows downward; flip so tip (-Y in SCAD) points down visually.
  let d = `M ${x0} ${-y0}`
  for (let i = 1; i < pts.length; i++) {
    const [x, y] = pts[i]
    d += ` L ${x} ${-y}`
  }
  return d + ' Z'
}

/** Sanity: every catalogued pick type has a profile. */
export function missingProfiles(): string[] {
  return PICK_TYPE_NAMES.filter((n) => !PROFILE_POINTS[n])
}
